apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alpaca
  name: alpaca-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alpaca
  type: NodePort
status:
  loadBalancer: {}