apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bandicoot
  name: bandicoot-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bandicoot
status:
  loadBalancer: {}