apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-env
spec:
  containers:
    - name: test-container
      image: nginx
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: auth-secret
            key:  admin