apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-new-3gb
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/3gb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pvc-2gb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual