# keybinding for reloading tmux
unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# change default leader key
set -g prefix C-g

# enable mouse support
set -g mouse on

# add vim navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Pane splits should open to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# catppuccin options
set-option -g status-position top


# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux' #https://www.youtube.com/watch?v=DzNmUNvnB04&t=21s

run '~/.tmux/plugins/tpm/tpm'
